apiVersion: v1
kind: Template
labels: {}
metadata:
  annotations:
    description: Template for setting up interconnect example
  labels:
    app: amq7-qpid
  name: amq7-qpid
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: amq-interconnect
    name: interconnect-a
  spec:
    replicas: 1
    selector:
      app: amq-interconnect
      deploymentconfig: interconnect-a
    template:
      metadata:
        labels:
          app: amq-interconnect
          deploymentconfig: interconnect-a
      spec:
        containers:
        - env:
          - name: AMQ_MODE
            value: "interconnect"
          - name: LOCALE
            value: "a"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 90
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 5672
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 5672
            timeoutSeconds: 1
          name: interconnect-a
          ports:
          - containerPort: 5672
            name: amqp
            protocol: TCP
          - containerPort: 5673
            name: console
            protocol: TCP
          - containerPort: 5674
            name: intra
            protocol: TCP
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - interconnect-a
        from:
          kind: ImageStreamTag
          name: amq7-image:latest
      type: ImageChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: amq-interconnect
    name: interconnect-b
  spec:
    replicas: 1
    selector:
      app: amq-interconnect
      deploymentconfig: interconnect-b
    template:
      metadata:
        labels:
          app: amq-interconnect
          deploymentconfig: interconnect-b
      spec:
        containers:
        - env:
          - name: AMQ_MODE
            value: "interconnect"
          - name: LOCALE
            value: "b"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 90
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 5672
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 5672
            timeoutSeconds: 1
          name: interconnect-b
          ports:
          - containerPort: 5672
            name: amqp
            protocol: TCP
          - containerPort: 5673
            name: console
            protocol: TCP
          - containerPort: 5674
            name: intra
            protocol: TCP
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - interconnect-b
        from:
          kind: ImageStreamTag
          name: amq7-image:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/dependencies: '[{"name":"interconnect-b","namespace":"","kind":"Service"}]'
    labels:
      app: amq-interconnect
    name: interconnect-a
  spec:
    ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: amqp
      nodePort: 30501
    - name: console
      protocol: TCP
      port: 5673
      targetPort: console
      nodePort: 30551
    - name: intra
      protocol: TCP
      port: 5674
      targetPort: intra
      nodePort: 30571
    type: LoadBalancer
    selector:
      app: amq-interconnect
      deploymentconfig: interconnect-a
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: amq-interconnect
    name: interconnect-b
  spec:
    ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: amqp
      nodePort: 30502
    - name: console
      protocol: TCP
      port: 5673
      targetPort: console
      nodePort: 30552
    - name: intra
      protocol: TCP
      port: 5674
      targetPort: intra
      nodePort: 30572
    type: LoadBalancer
    selector:
      app: amq-interconnect
      deploymentconfig: interconnect-b
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      description: Route for service.
    name: interconnect-a-1
    labels:
      app: interconnect-a-1
  spec:
    port:
      targetPort: 30501
    to:
      kind: "Service"
      name: "interconnect-a"
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      description: Route for service.
    name: interconnect-a-2
    labels:
      app: interconnect-a-2
  spec:
    port:
      targetPort: 30551
    to:
      kind: "Service"
      name: "interconnect-a"
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      description: Route for service.
    name: interconnect-a-3
    labels:
      app: interconnect-a-3
  spec:
    port:
      targetPort: 30571
    to:
      kind: "Service"
      name: "interconnect-a"
      
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      description: Route for service.
    name: interconnect-b-1
    labels:
      app: interconnect-b-1
  spec:
    port:
      targetPort: 30502
    to:
      kind: "Service"
      name: "interconnect-b"
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      description: Route for service.
    name: interconnect-b-2
    labels:
      app: interconnect-b-2
  spec:
    port:
      targetPort: 30552
    to:
      kind: "Service"
      name: "interconnect-b"
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      description: Route for service.
    name: interconnect-b-3
    labels:
      app: interconnect-b-3
  spec:
    port:
      targetPort: 30572
    to:
      kind: "Service"
      name: "interconnect-b"